export const clientFormFields = [
  {
    name: "apellidoCliente",
    id: "apellidoCliente",
    label: "Apellido",
    labelClassName: 'col-sm-2 col-form-label form-control-sm',
    type: "text",
    inputClassName: "form-control form-control-sm",
    placeholder: "Apellido ...",
    readOnly: true,
    required: true,
  },
  {
    name: "nombreCliente",
    id: "nombreCliente",
    label: "Nombre",
    labelClassName: 'col-sm-2 col-form-label form-control-sm',
    type: "text",
    inputClassName: "form-control form-control-sm",
    placeholder: "Nombre ...",
    readOnly: true,
    required: true,
  },
  {
    name: "celularCliente",
    id: "celularCliente",
    label: "Celular",
    labelClassName: 'col-sm-2 col-form-label form-control-sm',
    type: "number",
    inputClassName: "form-control form-control-sm",
    placeholder: "Celular ...",
    readOnly: true,
    required: true,
  },
  {
    name: "condIvaClient",
    id: "condIvaClient",
    label: "Condicion IVA",
    labelClassName: 'col-sm-2 col-form-label form-control-sm',
    type: "text",
    inputClassName: "form-control form-control-sm",
    placeholder: "Condicion IVA ...",
    readOnly: true,
    required: true,
  },
  {
    name: "cuitCliente",
    id: "cuitCliente",
    label: "CUIT / DNI",
    labelClassName: 'col-sm-2 col-form-label form-control-sm',
    type: "number",
    inputClassName: "form-control form-control-sm",
    placeholder: "CUIT / DNI ...",
    readOnly: true,
    required: true,
  },
  {
    name: "telefonoCliente",
    id: "telefonoCliente",
    label: "Telefono",
    labelClassName: 'col-sm-2 col-form-label form-control-sm',
    type: "number",
    inputClassName: "form-control form-control-sm",
    placeholder: "Telefono ...",
    readOnly: true,
    required: true,
  },
  {
    name: "mailCliente",
    id: "mailCliente",
    label: "Mail",
    labelClassName: 'col-sm-2 col-form-label form-control-sm',
    type: "email",
    inputClassName: "form-control form-control-sm",
    placeholder: "Mail ...",
    readOnly: true,
    required: true,
  },
];
